### ISSUE TITLE
Docker version - Error in absolute path

### ISSUE THREAD

**Issue by vlauciani** [italia/publiccode-parser-go#30] opened 2020-05-21 13:35 UTC
Hi all

Using docker version, the absolute path for `publiccode.yml` doesn't work; relative path works.

Example:
**1)** relative path:
```
$ docker run -it --rm -v $(pwd):/files --entrypoint="/bin/sh" italia/publiccode-parser-go
/ #
/ # /pcvalidate files/publiccode.yml
validation ok
/ #
```

**2)** absolute path:
```
$ docker run -it --rm -v $(pwd):/files --entrypoint="/bin/sh" italia/publiccode-parser-go
/ #
/ # /pcvalidate /files/publiccode.yml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x670936]

goroutine 1 [running]:
github.com/alranel/go-vcsurl.IsFile(0x0, 0xc0000e1e78)
	/go/src/github.com/alranel/go-vcsurl/vcsurl.go:90 +0x26
github.com/alranel/go-vcsurl.GetRawRoot(0x0, 0x0)
	/go/src/github.com/alranel/go-vcsurl/vcsurl.go:170 +0x2f
main.main()
	/go/src/github.com/italia/publiccode-parser-go/pcvalidate/pcvalidate.go:43 +0x610
/ #
```

**Comment by libremente** [comment] 2020-05-21 13:39
Hi @vlauciani, thanks for reporting. 
This is linked to #27, we are already investigating the cause, thanks for your patience!

**Comment by libremente** [comment] 2020-07-01 15:23
Seeing #31 I guess we can also close this one. WDYT @sebbalex?

**Comment by sebbalex** [comment] 2020-07-01 15:51
> Seeing #31 I guess we can also close this one. WDYT @sebbalex?

Yes! closed

**Closed by sebbalex** 2020-07-01 15:51 UTC
Labels: duplicate
